# coding=utf-8
"""
    Модуль содержит словари countries, genres для получения slug.
"""
from six import u


# `список стран <http://cinemate.cc/movie/country/>`_
countries = {
    'afghanistan': u('Афганистан'),
    'albania': u('Албания'),
    'algeria': u('Алжир'),
    'argentina': u('Аргентина'),
    'armenia': u('Армения'),
    'aruba': u('Аруба'),
    'austria': u('Австрия'),
    'azerbaijan': u('Азербайджан'),
    'bahamas': u('Багамы'),
    'bahrain': u('Бахрейн'),
    'bangladesh': u('Бангладеш'),
    'barbados': u('Барбадос'),
    'belarus': u('Беларусь'),
    'belgium': u('Бельгия'),
    'bhutan': u('Бутан'),
    'bolivia': u('Боливия'),
    'bosnia-and-herzegovina': u('Босния-Герцеговина'),
    'botswana': u('Ботсвана'),
    'brazil': u('Бразилия'),
    'bulgaria': u('Болгария'),
    'burkina-faso': u('Буркина-Фасо'),
    'cambodia': u('Камбоджа'),
    'cameroon': u('Камерун'),
    'canada': u('Канада'),
    'cape-verde': u('Кабо-Верде'),
    'chad': u('Чад'),
    'chile': u('Чили'),
    'china': u('Китай'),
    'colombia': u('Колумбия'),
    'costa-rica': u('Коста-Рика'),
    'croatia': u('Хорватия'),
    'cuba': u('Куба'),
    'cyprus': u('Кипр'),
    'czech-republic': u('Чехия'),
    'czechoslovakia': u('Чехословакия'),
    'denmark': u('Дания'),
    'dominican-republic': u('Доминиканская Республика'),
    'east-germany': u('Германия (ГДР)'),
    'ecuador': u('Эквадор'),
    'egypt': u('Египет'),
    'estonia': u('Эстония'),
    'ethiopia': u('Эфиопия'),
    'faroe-islands': u('Фарерские острова'),
    'federal-republic-yugoslavia': u('Союзная Республика Югославия'),
    'finland': u('Финляндия'),
    'france': u('Франция'),
    'georgia': u('Грузия'),
    'germany': u('Германия'),
    'ghana': u('Гана'),
    'greece': u('Греция'),
    'greenland': u('Гренландия'),
    'guatemala': u('Гватемала'),
    'haiti': u('Гаити'),
    'honduras': u('Гондурас'),
    'hong-kong': u('Гонконг'),
    'hungary': u('Венгрия'),
    'iceland': u('Исландия'),
    'india': u('Индия'),
    'indonesia': u('Индонезия'),
    'iran': u('Иран'),
    'iraq': u('Ирак'),
    'ireland': u('Ирландия'),
    'israel': u('Израиль'),
    'italy': u('Италия'),
    'ivory-coast': u('Берег Слоновой Кости'),
    'jamaica': u('Ямайка'),
    'japan': u('Япония'),
    'jordan': u('Иордания'),
    'kazakhstan': u('Казахстан'),
    'kenya': u('Кения'),
    'kuwait': u('Кувейт'),
    'kyrgyzstan': u('Кыргызстан'),
    'laos': u('Лаос'),
    'latvia': u('Латвия'),
    'lebanon': u('Ливан'),
    'lesotho': u('Лесото'),
    'liberia': u('Либерия'),
    'libya': u('Ливия'),
    'liechtenstein': u('Лихтенштейн'),
    'lithuania': u('Литва'),
    'luxembourg': u('Люксембург'),
    'macau': u('Макао'),
    'macedonia': u('Македония'),
    'malaysia': u('Малайзия'),
    'mali': u('Мали'),
    'malta': u('Мальта'),
    'mauritania': u('Мавритания'),
    'mexico': u('Мексика'),
    'moldova': u('Молдова'),
    'monaco': u('Монако'),
    'mongolia': u('Монголия'),
    'montenegro': u('Черногория'),
    'morocco': u('Марокко'),
    'mozambique': u('Мозамбик'),
    'namibia': u('Намибия'),
    'nepal': u('Непал'),
    'netherlands': u('Нидерланды'),
    'new-zealand': u('Новая Зеландия'),
    'nicaragua': u('Никарагуа'),
    'nigeria': u('Нигерия'),
    'north-korea': u('Северная Корея'),
    'norway': u('Норвегия'),
    'oman': u('Оман'),
    'pakistan': u('Пакистан'),
    'palestine': u('Палестина'),
    'panama': u('Панама'),
    'paraguay': u('Парагвай'),
    'peru': u('Перу'),
    'philippines': u('Филиппины'),
    'poland': u('Польша'),
    'portugal': u('Португалия'),
    'puerto-rico': u('Пуэрто-Рико'),
    'qatar': u('Катар'),
    'republic-of-macedonia': u('Республика Македония'),
    'romania': u('Румыния'),
    'russia': u('Россия'),
    'russian-empire': u('Российская империя'),
    'saudi-arabia': u('Саудовская Аравия'),
    'senegal': u('Сенегал'),
    'serbia': u('Сербия'),
    'serbia-and-montenegro': u('Сербия и Черногория'),
    'singapore': u('Сингапур'),
    'slovakia': u('Словакия'),
    'slovenia': u('Словения'),
    'somalia': u('Сомали'),
    'south-africa': u('ЮАР'),
    'south-korea': u('Корея Южная'),
    'soviet-union': u('СССР'),
    'spain': u('Испания'),
    'sri-lanka': u('Шри-Ланка'),
    'sweden': u('Швеция'),
    'switzerland': u('Швейцария'),
    'syria': u('Сирия'),
    'taiwan': u('Тайвань'),
    'tajikistan': u('Таджикистан'),
    'tanzania': u('Танзания'),
    'thailand': u('Таиланд'),
    'trinidad-and-tobago': u('Тринидад и Тобаго'),
    'tunisia': u('Тунис'),
    'turkey': u('Турция'),
    'turkmenistan': u('Туркменистан'),
    'uk': u('Великобритания'),
    'ukraine': u('Украина'),
    'united-arab-emirates': u('ОАЭ'),
    'uruguay': u('Уругвай'),
    'usa': u('США'),
    'uzbekistan': u('Узбекистан'),
    'venezuela': u('Венесуэла'),
    'vietnam': u('Вьетнам'),
    'west-germany': u('Германия (ФРГ)'),
    'yemen': u('Йемен'),
    'yugoslavia': u('Югославия'),
    'zambia': u('Замбия'),
    'zimbabwe': u('Зимбабве'),
}

# `список жанров <http://cinemate.cc/movie/genre/>`_
genres = {
    'action': u('боевик'),
    'adult': u('для взрослых'),
    'adventure': u('приключения'),
    'animation': u('мультфильм'),
    'anime': u('аниме'),
    'biography': u('биография'),
    'children': u('детский'),
    'comedy': u('комедия'),
    'concert': u('концерт'),
    'crime': u('криминал'),
    'documentary': u('документальный'),
    'drama': u('драма'),
    'family': u('семейный'),
    'fantasy': u('фэнтези'),
    'film-noir': u('фильм-нуар'),
    'game-show': u('телеигра'),
    'history': u('история'),
    'horror': u('ужасы'),
    'music': u('музыка'),
    'musical': u('мюзикл'),
    'mystery': u('детектив'),
    'news': u('новости'),
    'reality-tv': u('реалити шоу'),
    'romance': u('мелодрама'),
    'sci-fi': u('фантастика'),
    'short': u('короткометражка'),
    'sport': u('спорт'),
    'talk-show': u('ток-шоу'),
    'thriller': u('триллер'),
    'war': u('военный'),
    'western': u('вестерн'),
}
